language: php
php:
  - '5.6'

services:
  - mysql

before_script:
  - "mysql -e < curl -u ${DATABASE_USER}:${DATABASE_PW} "${DATABASE_URL}""

notifications:
  slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
  email: false

script:
  - cd application/tests/ && phpunit --coverage-text
  - php coverage-checker.php build/logs/clover.xml 100
